### ISSUE TITLE
Browser version not working

### ISSUE THREAD

**Issue by dorsharonfuse** [nbesli/pdf-merger-js#73]
The `browser.js` file is using `Buffer` which is not available on the browser.
I'm afraid beyond that some other stuff might not be compatible.

**Comment by mojoaxel** [comment]
Maybe @DanMHammer can have another look!?

**Comment by meirlamdan** [comment]
I also get an error.
i not sure if is the same problem.
`Uncaught ReferenceError: global is not defined
    at node_modules/readable-stream/lib/_stream_readable.js (_stream_readable.js:48:21)
    at __require (chunk-OL3AADLO.js?v=f485049a:9:50)
    at node_modules/readable-stream/readable-browser.js (readable-browser.js:1:28)
    at __require (chunk-OL3AADLO.js?v=f485049a:9:50)
    at node_modules/pdfjs/lib/document.js (document.js:7:18)
    at __require (chunk-OL3AADLO.js?v=f485049a:9:50)
    at node_modules/pdfjs/lib/index.js (index.js:3:20)
    at __require (chunk-OL3AADLO.js?v=f485049a:9:50)
    at node_modules/pdf-merger-js/browser.js (browser.js:1:13)
    at __require (chunk-OL3AADLO.js?v=f485049a:9:50)`

**Comment by Beej126** [comment]
in case it helps... the [need for Buffer in a React project has been solved here](https://dev.to/przpiw/react-pdf-rendering-4g7b)... and [here is my own working online sample](https://stackblitz.com/edit/react-pdf-demo2?file=craco.config.js) based on that approach... i'll post a working sample project if i wind up going this direction

**Comment by mojoaxel** [comment]
@dorsharonfuse @meirlamdan Please check if this is still an issue with [v4](https://github.com/nbesli/pdf-merger-js/releases?q=v4&expanded=true).

**Comment by nurullah** [comment]
> @dorsharonfuse @meirlamdan Please check if this is still an issue with [v4](https://github.com/nbesli/pdf-merger-js/releases?q=v4&expanded=true).

The problem continues for me. I still get the "Buffer is not defined" error.

**Comment by davbrito** [comment]
The browser version shouldn't use the node Buffer global. Instead should use an `ArrayBuffer` or an `Uint8Array`

**Comment by OtacilioN** [comment]
Same error @nurullah reported here trying to use web version:

````
Uncaught (in promise) ReferenceError: Buffer is not defined
    at PDFMerger._getInputAsBuffer (browser.js:43:1)
    at PDFMerger._addEntireDocument (browser.js:75:1)
    at PDFMerger.add (browser.js:11:1)
    at async render (index.js:134:1)
 
 `````
